### ISSUE TITLE
Plots not showing in output when used in rmarkdown

### ISSUE THREAD

**Issue by ablommae** [florianstijven/Surrogate-development#6]
Hello, minor issue, 

I tried using the plots in an rmakrdown creating a html report and plots are not showing.
Minimal example in txt in attachement, (.Rmd files cannot be attached, so to change extension when testing).

In the output plot is not showing

[testSurrogatePlot.txt](https://github.com/florianstijven/Surrogate-development/files/13885603/testSurrogatePlot.txt)

screenshot of output + sessionInfo

![image](https://github.com/florianstijven/Surrogate-development/assets/103417431/07afa77f-4b07-44b8-ab28-660a5afac230)

I thnk the dev.new in the function:

/R/plot.TrialLevelMA.R

 should be removed

Kind regards
Adriaan

**Comment by florianstijven** [comment]
Dear Adriaan,

Thank you for opening this issue. You're right that the call to dev.new() causes this issue. For unknown reasons, many plot() methods that were added some years ago contain calls to dev.new(). This issue will be resolved in the next update.

Kind regards,
Florian

**Comment by florianstijven** [comment]
This issue has been resolved in the development version. In the next release of the package to CRAN, this fix will be included.

Kind regards,
Florian
